apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: uj1bnyr79-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: uj1bnyr79-nodejs 
  name: uj1bnyr79-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: uj1bnyr79-nodejs 
